FROM node:22-slim

WORKDIR /app

RUN npm install -g pnpm@latest turbo

COPY . .

# Install dependencies (including those in apps/web)
RUN pnpm install

# Web app is configured to run on port 3001 in package.json
EXPOSE 3001
ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3001

CMD ["pnpm", "turbo", "run", "dev", "--filter=web"]
